In [101]:
#Importación de librerias
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# A) Introducción

In [102]:
#1. Lectura de los ficheros
part1 = pd.read_csv("world-data-2023_part1.csv", index_col=0)
part2 = pd.read_csv("world-data-2023_part2.csv", index_col=0)

In [103]:
#2. Identifica las columnas comunes entre los dos conjuntos de datos y analisis exploratorio inicial.
##df_wd23_part1
part1.head(1)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70

In [104]:
part1.shape

(195, 16)

In [105]:
part1.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='object')

In [106]:
part1.describe

<bound method NDFrame.describe of          Country Density\n(P/Km2) Abbreviation Agricultural Land( %)  \
0    Afghanistan               60           AF                58.10%
1        Albania              105           AL                43.10%
2        Algeria               18           DZ                17.40%
3        Andorra              164           AD                40.00%
4         Angola               26           AO                47.50%
..           ...              ...          ...                   ...
190    Venezuela               32           VE                24.50%
191      Vietnam              314           VN                39.30%
192        Yemen               56           YE                44.60%
193       Zambia               25           ZM                32.10%
194     Zimbabwe               38           ZW                41.90%

    Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0          652,230           323,000       32.49          93.0
1           28,748             9,000       11.78         355.0
2        2,381,741           317,000       24.28         213.0
3              468               NaN        7.20         376.0
4        1,246,700           117,000       40.73         244.0
..             ...               ...         ...           ...
190        912,050           343,000       17.88          58.0
191        331,210           522,000       16.75          84.0
192        527,968            40,000       30.45         967.0
193        752,618            16,000       36.19         260.0
194        390,757            51,000       30.68         263.0

    Capital/Major City Co2-Emissions       CPI CPI Change (%) Currency-Code  \
0                Kabul         8,672     149.9          2.30%           AFN
1               Tirana         4,536    119.05          1.40%           ALL
2              Algiers       150,006    151.36          2.00%           DZD
3     Andorra la Vella           469       NaN            NaN           EUR
4               Luanda        34,693    261.73         17.10%           AOA
..                 ...           ...       ...            ...           ...
190            Caracas       164,175  2,740.27        254.90%           VED
191              Hanoi       192,668    163.52          2.80%           VND
192              Sanaa        10,609    157.58          8.10%           YER
193             Lusaka         5,141    212.31          9.20%           ZMW
194             Harare        10,983    105.51          0.90%           NaN

     Fertility Rate Forested Area (%) Gasoline Price
0              4.47             2.10%         $0.70
1              1.62            28.10%         $1.36
2              3.02             0.80%         $0.28
3              1.27            34.00%         $1.51
4              5.52            46.30%         $0.97
..              ...               ...            ...
190            2.27            52.70%         $0.00
191            2.05            48.10%         $0.80
192            3.79             1.00%         $0.92
193            4.63            65.20%         $1.40
194            3.62            35.50%         $1.34

[195 rows x 16 columns]>

In [107]:
##df_wd23_part2
part2.head(1)

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"

In [108]:
part2.shape

(195, 19)

In [109]:
part2.columns

Index(['GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'country',
       'coordinates'],
      dtype='object')

In [110]:
part2.describe

<bound method NDFrame.describe of                    GDP Gross primary education enrollment (%)  \
0     $19,101,353,833                                 104.00%
1     $15,278,077,447                                 107.00%
2    $169,988,236,398                                 109.90%
3      $3,154,057,987                                 106.40%
4     $94,635,415,870                                 113.50%
..                 ...                                    ...
190  $482,359,318,768                                  97.20%
191  $261,921,244,843                                 110.60%
192   $26,914,402,224                                  93.60%
193   $23,064,722,446                                  98.70%
194   $21,440,758,800                                 109.90%

    Gross tertiary education enrollment (%)  Infant mortality  \
0                                     9.70%              47.9
1                                    55.00%               7.8
2                                    51.40%              20.1
3                                       NaN               2.7
4                                     9.30%              51.6
..                                      ...               ...
190                                  79.30%              21.4
191                                  28.50%              16.5
192                                  10.20%              42.9
193                                   4.10%              40.4
194                                  10.00%              33.9

         Largest city  Life expectancy  Maternal mortality ratio Minimum wage  \
0               Kabul             64.5                     638.0       $0.43
1              Tirana             78.5                      15.0       $1.12
2             Algiers             76.7                     112.0       $0.95
3    Andorra la Vella              NaN                       NaN       $6.63
4              Luanda             60.8                     241.0       $0.71
..                ...              ...                       ...          ...
190           Caracas             72.1                     125.0       $0.01
191  Ho Chi Minh City             75.3                      43.0       $0.73
192             Sanaa             66.1                     164.0          NaN
193            Lusaka             63.5                     213.0       $0.24
194            Harare             61.2                     458.0          NaN

    Official language Out of pocket health expenditure  \
0              Pashto                           78.40%
1            Albanian                           56.90%
2              Arabic                           28.10%
3             Catalan                           36.40%
4          Portuguese                           33.40%
..                ...                              ...
190           Spanish                           45.80%
191        Vietnamese                           43.50%
192            Arabic                           81.00%
193           English                           27.50%
194             Shona                           25.80%

     Physicians per thousand  Population  \
0                       0.28  38,041,754
1                       1.20   2,854,191
2                       1.72  43,053,054
3                       3.33      77,142
4                       0.21  31,825,295
..                       ...         ...
190                     1.92  28,515,829
191                     0.82  96,462,106
192                     0.31  29,161,922
193                     1.19  17,861,030
194                     0.21  14,645,468

    Population: Labor force participation (%) Tax revenue (%) Total tax rate  \
0                                      48.90%           9.30%         71.40%
1                                      55.70%          18.60%         36.60%
2                                      41.20%          37.20%         66.10%
3                                         NaN             NaN            NaN
4                                      77.50%           9.20%         49.10%
..                                        ...             ...            ...
190                                    59.70%             NaN         73.30%
191                                    77.40%          19.10%         37.60%
192                                    38.00%             NaN         26.60%
193                                    74.60%          16.20%         15.60%
194                                    83.10%          20.70%         31.60%

    Unemployment rate Urban_population      country  \
0              11.12%        9,797,273  Afghanistan
1              12.33%        1,747,593      Albania
2              11.70%       31,510,100      Algeria
3                 NaN           67,873      Andorra
4               6.89%       21,061,025       Angola
..                ...              ...          ...
190             8.80%       25,162,368    Venezuela
191             2.01%       35,332,140      Vietnam
192            12.91%       10,869,523        Yemen
193            11.43%        7,871,713       Zambia
194             4.95%        4,717,305     Zimbabwe

                      coordinates
0      ('33.93911 ', '67.709953')
1     ('41.153332 ', '20.168331')
2      ('28.033886 ', '1.659626')
3      ('42.506285 ', '1.521801')
4    ('-11.202692 ', '17.873887')
..                            ...
190     ('6.42375 ', '-66.58973')
191  ('14.058324 ', '108.277199')
192   ('15.552727 ', '48.516388')
193  ('-13.133897 ', '27.849332')
194  ('-19.015438 ', '29.154857')

[195 rows x 19 columns]>

In [111]:
#3. Unión de los ficheros
## Como la columna country no tiene el mismo formato hay que renombar las columnas 

part1.rename(columns={'Country': 'country'}, inplace=True)
part2.rename(columns={'country': 'country'}, inplace=True)

In [112]:
merged_data = pd.merge(part1, part2, on='country', suffixes=('_part1', '_part2'))

In [113]:
merged_data.to_csv('world-data-2023-vf.csv', index=False)

In [114]:
df_vf = pd.read_csv("world-data-2023-vf.csv", index_col=0)

In [115]:
df_vf.head()

,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"

In [116]:
df_vf.columns

Index(['Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population',
       'coordinates'],
      dtype='object')

In [117]:
df_vf.shape

(195, 33)

In [118]:
df_vf.describe()

,Birth Rate,Calling Code,Fertility Rate,Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand
count,189.000000,194.000000,188.000000,189.000000,187.000000,181.000000,188.000000
mean,20.214974,360.546392,2.698138,21.332804,72.279679,160.392265,1.839840
std,9.945774,323.236419,1.282267,19.548058,7.483661,233.502024,1.684261
min,5.900000,1.000000,0.980000,1.400000,52.800000,2.000000,0.010000
25%,11.300000,82.500000,1.705000,6.000000,67.000000,13.000000,0.332500
50%,17.950000,255.500000,2.245000,14.000000,73.200000,53.000000,1.460000
75%,28.750000,506.750000,3.597500,32.700000,77.500000,186.000000,2.935000
max,46.080000,1876.000000,6.910000,84.500000,85.400000,1150.000000,8.420000

In [119]:
numeric_columns = df_vf.select_dtypes(include='number').columns
numeric_columns

Index(['Birth Rate', 'Calling Code', 'Fertility Rate', 'Infant mortality',
       'Life expectancy', 'Maternal mortality ratio',
       'Physicians per thousand'],
      dtype='object')

# B) Ejercicios de Limpieza

Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

In [120]:

#2.Los nombres de las columnas no son homogeneos.
## Espacios vacios
df_vf.rename(columns=lambda x: x.replace(' ', ''), inplace=True)

In [121]:
df_vf.rename(columns=lambda x: x.replace(' ', '').replace('\n', '').replace(':', '').replace(r'\(.*\)', '').lower(), inplace=True)
print(df_vf.head())

            density(p/km2) abbreviation agriculturalland(%) landarea(km2)  \
country
Afghanistan             60           AF              58.10%       652,230
Albania                105           AL              43.10%        28,748
Algeria                 18           DZ              17.40%     2,381,741
Andorra                164           AD              40.00%           468
Angola                  26           AO              47.50%     1,246,700

            armedforcessize  birthrate  callingcode capital/majorcity  \
country
Afghanistan         323,000      32.49         93.0             Kabul
Albania               9,000      11.78        355.0            Tirana
Algeria             317,000      24.28        213.0           Algiers
Andorra                 NaN       7.20        376.0  Andorra la Vella
Angola              117,000      40.73        244.0            Luanda

            co2-emissions     cpi cpichange(%) currency-code  fertilityrate  \
country
Afghanistan         8,672   149.9        2.30%           AFN           4.47
Albania             4,536  119.05        1.40%           ALL           1.62
Algeria           150,006  151.36        2.00%           DZD           3.02
Andorra               469     NaN          NaN           EUR           1.27
Angola             34,693  261.73       17.10%           AOA           5.52

            forestedarea(%) gasolineprice                gdp  \
country
Afghanistan           2.10%        $0.70    $19,101,353,833
Albania              28.10%        $1.36    $15,278,077,447
Algeria               0.80%        $0.28   $169,988,236,398
Andorra              34.00%        $1.51     $3,154,057,987
Angola               46.30%        $0.97    $94,635,415,870

            grossprimaryeducationenrollment(%)  \
country
Afghanistan                            104.00%
Albania                                107.00%
Algeria                                109.90%
Andorra                                106.40%
Angola                                 113.50%

            grosstertiaryeducationenrollment(%)  infantmortality  \
country
Afghanistan                               9.70%             47.9
Albania                                  55.00%              7.8
Algeria                                  51.40%             20.1
Andorra                                     NaN              2.7
Angola                                    9.30%             51.6

                  largestcity  lifeexpectancy  maternalmortalityratio  \
country
Afghanistan             Kabul            64.5                   638.0
Albania                Tirana            78.5                    15.0
Algeria               Algiers            76.7                   112.0
Andorra      Andorra la Vella             NaN                     NaN
Angola                 Luanda            60.8                   241.0

            minimumwage officiallanguage outofpockethealthexpenditure  \
country
Afghanistan      $0.43            Pashto                       78.40%
Albania          $1.12          Albanian                       56.90%
Algeria          $0.95            Arabic                       28.10%
Andorra          $6.63           Catalan                       36.40%
Angola           $0.71        Portuguese                       33.40%

             physiciansperthousand  population  \
country
Afghanistan                   0.28  38,041,754
Albania                       1.20   2,854,191
Algeria                       1.72  43,053,054
Andorra                       3.33      77,142
Angola                        0.21  31,825,295

            populationlaborforceparticipation(%) taxrevenue(%) totaltaxrate  \
country
Afghanistan                               48.90%         9.30%       71.40%
Albania                                   55.70%        18.60%       36.60%
Algeria                                   41.20%        37.20%       66.10%
Andorra                                      NaN           NaN          NaN
Angola                                    77.50%         9.20%       49.10%

            unemploymentrate urban_population                   coordinates
country
Afghanistan           11.12%        9,797,273    ('33.93911 ', '67.709953')
Albania               12.33%        1,747,593   ('41.153332 ', '20.168331')
Algeria               11.70%       31,510,100    ('28.033886 ', '1.659626')
Andorra                  NaN           67,873    ('42.506285 ', '1.521801')
Angola                 6.89%       21,061,025  ('-11.202692 ', '17.873887')

In [122]:
##3·La columnas  tiene la latitud y la longitud en una sola columna. 
#Dividir la columna "coordinates" en dos columnas separadas de longitud y latit
df_vf[['longitude', 'latitude']] = df_vf['coordinates'].str.split(',', expand=True)
print(df_vf.head())

            density(p/km2) abbreviation agriculturalland(%) landarea(km2)  \
country
Afghanistan             60           AF              58.10%       652,230
Albania                105           AL              43.10%        28,748
Algeria                 18           DZ              17.40%     2,381,741
Andorra                164           AD              40.00%           468
Angola                  26           AO              47.50%     1,246,700

            armedforcessize  birthrate  callingcode capital/majorcity  \
country
Afghanistan         323,000      32.49         93.0             Kabul
Albania               9,000      11.78        355.0            Tirana
Algeria             317,000      24.28        213.0           Algiers
Andorra                 NaN       7.20        376.0  Andorra la Vella
Angola              117,000      40.73        244.0            Luanda

            co2-emissions     cpi cpichange(%) currency-code  fertilityrate  \
country
Afghanistan         8,672   149.9        2.30%           AFN           4.47
Albania             4,536  119.05        1.40%           ALL           1.62
Algeria           150,006  151.36        2.00%           DZD           3.02
Andorra               469     NaN          NaN           EUR           1.27
Angola             34,693  261.73       17.10%           AOA           5.52

            forestedarea(%) gasolineprice                gdp  \
country
Afghanistan           2.10%        $0.70    $19,101,353,833
Albania              28.10%        $1.36    $15,278,077,447
Algeria               0.80%        $0.28   $169,988,236,398
Andorra              34.00%        $1.51     $3,154,057,987
Angola               46.30%        $0.97    $94,635,415,870

            grossprimaryeducationenrollment(%)  \
country
Afghanistan                            104.00%
Albania                                107.00%
Algeria                                109.90%
Andorra                                106.40%
Angola                                 113.50%

            grosstertiaryeducationenrollment(%)  infantmortality  \
country
Afghanistan                               9.70%             47.9
Albania                                  55.00%              7.8
Algeria                                  51.40%             20.1
Andorra                                     NaN              2.7
Angola                                    9.30%             51.6

                  largestcity  lifeexpectancy  maternalmortalityratio  \
country
Afghanistan             Kabul            64.5                   638.0
Albania                Tirana            78.5                    15.0
Algeria               Algiers            76.7                   112.0
Andorra      Andorra la Vella             NaN                     NaN
Angola                 Luanda            60.8                   241.0

            minimumwage officiallanguage outofpockethealthexpenditure  \
country
Afghanistan      $0.43            Pashto                       78.40%
Albania          $1.12          Albanian                       56.90%
Algeria          $0.95            Arabic                       28.10%
Andorra          $6.63           Catalan                       36.40%
Angola           $0.71        Portuguese                       33.40%

             physiciansperthousand  population  \
country
Afghanistan                   0.28  38,041,754
Albania                       1.20   2,854,191
Algeria                       1.72  43,053,054
Andorra                       3.33      77,142
Angola                        0.21  31,825,295

            populationlaborforceparticipation(%) taxrevenue(%) totaltaxrate  \
country
Afghanistan                               48.90%         9.30%       71.40%
Albania                                   55.70%        18.60%       36.60%
Algeria                                   41.20%        37.20%       66.10%
Andorra                                      NaN           NaN          NaN
Angola                                    77.50%         9.20%       49.10%

            unemploymentrate urban_population                   coordinates  \
country
Afghanistan           11.12%        9,797,273    ('33.93911 ', '67.709953')
Albania               12.33%        1,747,593   ('41.153332 ', '20.168331')
Algeria               11.70%       31,510,100    ('28.033886 ', '1.659626')
Andorra                  NaN           67,873    ('42.506285 ', '1.521801')
Angola                 6.89%       21,061,025  ('-11.202692 ', '17.873887')

                  longitude       latitude
country
Afghanistan    ('33.93911 '   '67.709953')
Albania       ('41.153332 '   '20.168331')
Algeria       ('28.033886 '    '1.659626')
Andorra       ('42.506285 '    '1.521801')
Angola       ('-11.202692 '   '17.873887')

In [123]:
print(df_vf.columns)

Index(['density(p/km2)', 'abbreviation', 'agriculturalland(%)',
       'landarea(km2)', 'armedforcessize', 'birthrate', 'callingcode',
       'capital/majorcity', 'co2-emissions', 'cpi', 'cpichange(%)',
       'currency-code', 'fertilityrate', 'forestedarea(%)', 'gasolineprice',
       'gdp', 'grossprimaryeducationenrollment(%)',
       'grosstertiaryeducationenrollment(%)', 'infantmortality', 'largestcity',
       'lifeexpectancy', 'maternalmortalityratio', 'minimumwage',
       'officiallanguage', 'outofpockethealthexpenditure',
       'physiciansperthousand', 'population',
       'populationlaborforceparticipation(%)', 'taxrevenue(%)', 'totaltaxrate',
       'unemploymentrate', 'urban_population', 'coordinates', 'longitude',
       'latitude'],
      dtype='object')

In [124]:
# Eliminar  la columna "coordinates" 
df_vf.drop(columns=['coordinates'], inplace=True)

In [125]:
print(df_vf.columns)

Index(['density(p/km2)', 'abbreviation', 'agriculturalland(%)',
       'landarea(km2)', 'armedforcessize', 'birthrate', 'callingcode',
       'capital/majorcity', 'co2-emissions', 'cpi', 'cpichange(%)',
       'currency-code', 'fertilityrate', 'forestedarea(%)', 'gasolineprice',
       'gdp', 'grossprimaryeducationenrollment(%)',
       'grosstertiaryeducationenrollment(%)', 'infantmortality', 'largestcity',
       'lifeexpectancy', 'maternalmortalityratio', 'minimumwage',
       'officiallanguage', 'outofpockethealthexpenditure',
       'physiciansperthousand', 'population',
       'populationlaborforceparticipation(%)', 'taxrevenue(%)', 'totaltaxrate',
       'unemploymentrate', 'urban_population', 'longitude', 'latitude'],
      dtype='object')

In [126]:
##4·Elimina los "%" de los valores de las columnas 

columnas = ['unemploymentrate', 'totaltaxrate', 'taxrevenue(%)', 'populationlaborforceparticipation(%)', 'outofpockethealthexpenditure', 'grosstertiaryeducationenrollment(%)', 'grossprimaryeducationenrollment(%)', 'forestedarea(%)', 'cpichange(%)', 'agriculturalland(%)']


df_vf[columnas] = df_vf[columnas].replace('%', '', regex=True)

In [127]:
df_vf.head(2)

,density(p/km2),abbreviation,agriculturalland(%),landarea(km2),armedforcessize,birthrate,callingcode,capital/majorcity,co2-emissions,cpi,cpichange(%),currency-code,fertilityrate,forestedarea(%),gasolineprice,gdp,grossprimaryeducationenrollment(%),grosstertiaryeducationenrollment(%),infantmortality,largestcity,lifeexpectancy,maternalmortalityratio,minimumwage,officiallanguage,outofpockethealthexpenditure,physiciansperthousand,population,populationlaborforceparticipation(%),taxrevenue(%),totaltaxrate,unemploymentrate,urban_population,longitude,latitude
country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,60,AF,58.10,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30,AFN,4.47,2.10,$0.70,"$19,101,353,833",104.00,9.70,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40,0.28,"38,041,754",48.90,9.30,71.40,11.12,"9,797,273",('33.93911 ','67.709953')
Albania,105,AL,43.10,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40,ALL,1.62,28.10,$1.36,"$15,278,077,447",107.00,55.00,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90,1.20,"2,854,191",55.70,18.60,36.60,12.33,"1,747,593",('41.153332 ','20.168331')

In [ ]:
##5. Eliminar $ Columnas de gasoline_price, gdp, minimum_wage, pero eliminando "$".

In [131]:
# Columnas que contienen el símbolo "$"
columnas_dollar = ['gasolineprice', 'gdp', 'minimumwage']

# Eliminar el símbolo "$" de los valores en las columnas especificadas
df_vf[columnas_dollar] = df_vf[columnas_dollar].replace('$', '', regex=False)

# Mostrar información estadística sobre las columnas seleccionadas
print(df_vf[columnas_dollar].describe())

       gasolineprice              gdp minimumwage
count            175              193         150
unique           101              193         114
top            0.71   19,101,353,833        0.41
freq               6                1           3

In [132]:
df_vf.to_csv('df_vf_modificado.csv', index=False)

# C) Ejercicios de Filtrado

In [145]:
#1. Países cuya mortalidad infantil esté entre 40 y 50 personas por kilómetro cuadrado.
paises_mortalidad_infantil = df_vf[(df_vf['infantmortality'] >= 40) & (df_vf['infantmortality'] <= 50)]
print(paises_mortalidad_infantil)

             density(p/km2) abbreviation agriculturalland(%) landarea(km2)  \
country
Afghanistan              60           AF               58.10       652,230
Burkina Faso             76           BF               44.20       274,200
Burundi                 463           BI               79.20        27,830
Djibouti                 43           DJ               73.40        23,200
Haiti                   414           HT               66.80        27,750
Kiribati                147           KI               42.00           811
Niger                    19           NE               36.10     1,267,000
Sudan                    25           SD               28.70     1,861,484
Togo                    152           TG               70.20        56,785
Yemen                    56           YE               44.60       527,968
Zambia                   25           ZM               32.10       752,618

             armedforcessize  birthrate  callingcode capital/majorcity  \
country
Afghanistan          323,000      32.49         93.0             Kabul
Burkina Faso          11,000      37.93        226.0       Ouagadougou
Burundi               31,000      39.01        257.0         Bujumbura
Djibouti              13,000      21.47        253.0     Djibouti City
Haiti                      0      24.35        509.0    Port-au-Prince
Kiribati                 NaN      27.89        686.0      South Tarawa
Niger                 10,000      46.08        227.0            Niamey
Sudan                124,000      32.18        249.0          Khartoum
Togo                  10,000      33.11        228.0              Lom�
Yemen                 40,000      30.45        967.0             Sanaa
Zambia                16,000      36.19        260.0            Lusaka

             co2-emissions       cpi cpichange(%) currency-code  \
country
Afghanistan          8,672     149.9         2.30           AFN
Burkina Faso         3,418    106.58        -3.20           XOF
Burundi                495    182.11        -0.70           BIF
Djibouti               620    120.25         3.30           DJF
Haiti                2,978    179.29        12.50           HTG
Kiribati                66     99.55         0.60           AUD
Niger                2,017    109.32        -2.50           XOF
Sudan               20,000  1,344.19        51.00           SDG
Togo                 3,000     113.3         0.70           XOF
Yemen               10,609    157.58         8.10           YER
Zambia               5,141    212.31         9.20           ZMW

              fertilityrate forestedarea(%) gasolineprice              gdp  \
country
Afghanistan            4.47            2.10         0.70   19,101,353,833
Burkina Faso           5.19           19.30         0.98   15,745,810,235
Burundi                5.41           10.90         1.21    3,012,334,882
Djibouti               2.73            0.20         1.32    3,318,716,359
Haiti                  2.94            3.50         0.81    8,498,981,821
Kiribati               3.57           15.00           NaN     194,647,202
Niger                  6.91            0.90         0.88   12,928,145,120
Sudan                  4.41            8.10         0.95   18,902,284,476
Togo                   4.32            3.10         0.71    5,459,979,417
Yemen                  3.79            1.00         0.92   26,914,402,224
Zambia                 4.63           65.20         1.40   23,064,722,446

             grossprimaryeducationenrollment(%)  \
country
Afghanistan                              104.00
Burkina Faso                              96.10
Burundi                                  121.40
Djibouti                                  75.30
Haiti                                    113.60
Kiribati                                 101.30
Niger                                     74.70
Sudan                                     76.80
Togo                                     123.80
Yemen                                     93.60
Zambia                                    98.70

             grosstertiaryeducationenrollment(%)  infantmortality  \
country
Afghanistan                                 9.70             47.9
Burkina Faso                                6.50             49.0
Burundi                                     6.10             41.0
Djibouti                                    5.30             49.8
Haiti                                       1.10             49.5
Kiribati                                     NaN             41.2
Niger                                       4.40             48.0
Sudan                                      16.90             42.1
Togo                                       14.50             47.4
Yemen                                      10.20             42.9
Zambia                                      4.10             40.4

                 largestcity  lifeexpectancy  maternalmortalityratio  \
country
Afghanistan            Kabul            64.5                   638.0
Burkina Faso     Ouagadougou            61.2                   320.0
Burundi            Bujumbura            61.2                   548.0
Djibouti       Djibouti City            66.6                   248.0
Haiti         Port-au-Prince            63.7                   480.0
Kiribati        South Tarawa            68.1                    92.0
Niger                 Niamey            62.0                   509.0
Sudan               Omdurman            65.1                   295.0
Togo                    Lom�            60.8                   396.0
Yemen                  Sanaa            66.1                   164.0
Zambia                Lusaka            63.5                   213.0

             minimumwage officiallanguage outofpockethealthexpenditure  \
country
Afghanistan        0.43            Pashto                        78.40
Burkina Faso       0.34            French                        36.10
Burundi              NaN          Kirundi                        19.10
Djibouti             NaN           French                        20.40
Haiti              0.25            French                        36.30
Kiribati             NaN          English                         0.20
Niger              0.29            French                        52.30
Sudan              0.41            Arabic                        63.20
Togo               0.34            French                        51.00
Yemen                NaN           Arabic                        81.00
Zambia             0.24           English                        27.50

              physiciansperthousand  population  \
country
Afghanistan                    0.28  38,041,754
Burkina Faso                   0.08  20,321,378
Burundi                        0.10  11,530,580
Djibouti                       0.22     973,560
Haiti                          0.23  11,263,077
Kiribati                       0.20     117,606
Niger                          0.04  23,310,715
Sudan                          0.26  42,813,238
Togo                           0.08   8,082,366
Yemen                          0.31  29,161,922
Zambia                         1.19  17,861,030

             populationlaborforceparticipation(%) taxrevenue(%) totaltaxrate  \
country
Afghanistan                                 48.90          9.30        71.40
Burkina Faso                                66.40         15.00        41.30
Burundi                                     79.20         13.60        41.20
Djibouti                                    60.20           NaN        37.90
Haiti                                       67.20           NaN        42.70
Kiribati                                      NaN         22.00        32.70
Niger                                       72.00         11.80        47.20
Sudan                                       48.40          8.00        45.40
Togo                                        77.60         16.90        48.20
Yemen                                       38.00           NaN        26.60
Zambia                                      74.60         16.20        15.60

             unemploymentrate urban_population       longitude  \
country
Afghanistan             11.12        9,797,273    ('33.93911 '
Burkina Faso             6.26        6,092,349   ('12.238333 '
Burundi                  1.43        1,541,177   ('-3.373056 '
Djibouti                10.30          758,549   ('11.825138 '
Haiti                   13.78        6,328,948   ('18.971187 '
Kiribati                  NaN           64,489   ('1.8368976 '
Niger                    0.47        3,850,231   ('17.607789 '
Sudan                   16.53       14,957,233   ('12.862807 '
Togo                     2.04        3,414,638    ('8.619543 '
Yemen                   12.91       10,869,523   ('15.552727 '
Zambia                  11.43        7,871,713  ('-13.133897 '

                      latitude
country
Afghanistan       '67.709953')
Burkina Faso      '-1.561593')
Burundi           '29.918886')
Djibouti          '42.590275')
Haiti            '-72.285215')
Kiribati       '-157.3768317')
Niger              '8.081666')
Sudan             '30.217636')
Togo               '0.824782')
Yemen             '48.516388')
Zambia            '27.849332')

In [147]:

#2.Encuentra los países cuyas tasas de natalidad son mayores o iguales a 20 y su esperanza de vida es mayor de 75 años.

paises_seleccionados = df_vf[(df_vf['birthrate'] >= 20) & (df_vf['lifeexpectancy'] > 75)]

# Mostrar los países seleccionados
print(paises_seleccionados)

         density(p/km2) abbreviation agriculturalland(%) landarea(km2)  \
country
Algeria              18           DZ               17.40     2,381,741
Honduras             89           HN               28.90       112,090
Israel              400           IL               24.60        20,770

         armedforcessize  birthrate  callingcode capital/majorcity  \
country
Algeria          317,000      24.28        213.0           Algiers
Honduras          23,000      21.60        504.0       Tegucigalpa
Israel           178,000      20.80        972.0         Jerusalem

         co2-emissions     cpi cpichange(%) currency-code  fertilityrate  \
country
Algeria        150,006  151.36         2.00           DZD           3.02
Honduras         9,813  150.34         4.40           HNL           2.46
Israel          65,166  108.15         0.80           ILS           3.09

         forestedarea(%) gasolineprice               gdp  \
country
Algeria             0.80         0.28   169,988,236,398
Honduras           40.00         0.98    25,095,395,475
Israel              7.70         1.57   395,098,666,122

         grossprimaryeducationenrollment(%)  \
country
Algeria                              109.90
Honduras                              91.50
Israel                               104.90

         grosstertiaryeducationenrollment(%)  infantmortality  largestcity  \
country
Algeria                                51.40             20.1      Algiers
Honduras                               26.20             15.1  Tegucigalpa
Israel                                 63.40              3.0    Jerusalem

          lifeexpectancy  maternalmortalityratio minimumwage officiallanguage  \
country
Algeria             76.7                   112.0       0.95            Arabic
Honduras            75.1                    65.0       1.01           Spanish
Israel              82.8                     3.0       7.58            Hebrew

         outofpockethealthexpenditure  physiciansperthousand  population  \
country
Algeria                         28.10                   1.72  43,053,054
Honduras                        49.10                   0.31   9,746,117
Israel                          24.40                   4.62   9,053,300

         populationlaborforceparticipation(%) taxrevenue(%) totaltaxrate  \
country
Algeria                                 41.20         37.20        66.10
Honduras                                68.80         17.30        39.10
Israel                                  64.00         23.10        25.30

         unemploymentrate urban_population      longitude        latitude
country
Algeria             11.70       31,510,100  ('28.033886 '     '1.659626')
Honduras             5.39        5,626,433  ('15.199999 '   '-86.241905')
Israel               3.86        8,374,393  ('31.046051 '    '34.851612')

In [ ]:
#3. Encuentra las ciudades cuyos paises contienen la palabra "la" en su nombre.

In [157]:

# Seleccionar las ciudades cuyos países contienen la palabra "la" en su nombre
df_vf_cleaned = df_vf.dropna(subset=['largestcity']) #eliminamos los NA de largestcity
ciudades_seleccionadas = df_vf_cleaned[df_vf_cleaned['largestcity'].str.contains('la', case=False)]
print(ciudades_seleccionadas['largestcity'])

country
Andorra                          Andorra la Vella
Bolivia                   Santa Cruz de la Sierra
Bosnia and Herzegovina               Tuzla Canton
Cameroon                                   Douala
Equatorial Guinea                          Malabo
Guatemala                          Guatemala City
Mongolia                              Ulaanbaatar
Morocco                                Casablanca
New Zealand                              Auckland
Nigeria                                     Lagos
Philippines                                Manila
Slovakia                               Bratislava
Tanzania                            Dar es Salaam
Vanuatu                                 Port Vila
Name: largestcity, dtype: object

In [177]:
#4. países cuyos medicos por cada 1000 habitantes (physicians_per_thousand) sea mayores de 5.
paises_seleccionados = df_vf[df_vf['physiciansperthousand'] > 5]

print("\n Paises con mas de medicos :\n")
print(paises_seleccionados['physiciansperthousand'])

 Paises con mas de medicos :

country
Austria       5.17
Belarus       5.19
Cuba          8.42
Georgia       7.12
Greece        5.48
Lithuania     6.35
Monaco        6.56
Portugal      5.12
San Marino    6.11
Uruguay       5.05
Name: physiciansperthousand, dtype: float64

In [178]:

#5.Encuentra los países cuyatasa de fertilidad sea mayor a 6.
paises_fertilidad = df_vf[df_vf['fertilityrate'] > 6]
paises_fertilidad
print(paises_fertilidad['fertilityrate'])

country
Niger      6.91
Somalia    6.07
Name: fertilityrate, dtype: float64

In [ ]:
#6. Países cuya moneda es el euro (EUR) y tienen una tasa de natalidad superior al promedio.

In [181]:
promedio_natalidad = df_vf['birthrate'].mean()

paises_euro = df_vf[df_vf['currency-code'] == 'EUR']

paises_seleccionados = paises_euro[paises_euro['birthrate'] > promedio_natalidad]
print(paises_seleccionados[['birthrate', 'currency-code']])

Empty DataFrame
Columns: [birthrate, currency-code]
Index: []

In [183]:
# Seleccionar los países cuyas tasas de mortalidad infantil son superiores a 70
paises_seleccionados = df_vf[df_vf['infantmortality'] > 70]

# Mostrar los países seleccionados
print(paises_seleccionados[ 'infantmortality'])

country
Central African Republic    84.5
Chad                        71.4
Nigeria                     75.7
Sierra Leone                78.5
Somalia                     76.6
Name: infantmortality, dtype: float64